[package]
name = "liquidex_websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.19"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lwk_wollet = { path = "../lwk/lwk_wollet" }

[patch.crates-io]
lwk_wollet = { path = "../lwk/lwk_wollet" }
lwk_common = { path = "../lwk/lwk_common" }
